[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
itertools = "0.13.0"
regex = "1.11.1"
thiserror = "2.0.7"
